# Generated by Django 3.1 on 2020-08-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('religion', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
    ]
